backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "images/uploads"

collections:
  - name: "products"
    label: "제품 관리"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "카테고리", name: "category", widget: "select", options: ["선회베어링", "고정밀기어", "CNC가공부품"] }
      - { label: "제품명", name: "title", widget: "string" }
      - { label: "제품 사진", name: "image", widget: "image" }
      - { label: "제품 상세설명", name: "body", widget: "markdown" }
